In [82]:
import pandas as pd
df = pd.read_csv(r'C:\Users\uwmap\OneDrive\Documents\Usamah\Data-BI Analysis\Datasets\Marketing Campaign\marketing_campaign.csv', sep=';')
print(df.head())

     ID  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0  5524        1957  Graduation         Single  58138.0        0         0
1  2174        1954  Graduation         Single  46344.0        1         1
2  4141        1965  Graduation       Together  71613.0        0         0
3  6182        1984  Graduation       Together  26646.0        1         0
4  5324        1981         PhD        Married  58293.0        1         0

  Dt_Customer  Recency  MntWines  ...  NumWebVisitsMonth  AcceptedCmp3  \
0  2012-09-04       58       635  ...                  7             0
1  2014-03-08       38        11  ...                  5             0
2  2013-08-21       26       426  ...                  4             0
3  2014-02-10       26        11  ...                  6             0
4  2014-01-19       94       173  ...                  5             0

   AcceptedCmp4  AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  \
0             0             0             0             0         0
1             0             0             0             0         0
2             0             0             0             0         0
3             0             0             0             0         0
4             0             0             0             0         0

   Z_CostContact  Z_Revenue  Response
0              3         11         1
1              3         11         0
2              3         11         0
3              3         11         0
4              3         11         0

[5 rows x 29 columns]

In [83]:
df_copy = df.copy()
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [84]:
df_copy = df_copy.drop(['Z_CostContact', 'Z_Revenue'], axis=1)
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Response             2240 non-null   int64
dtypes: float64(1), int64(23), object(3)
memory usage: 472.6+ KB

In [85]:
df_copy['TotalSpent'] = df_copy['MntWines'] + df_copy['MntFruits'] + df_copy['MntMeatProducts'] + df_copy['MntFishProducts'] + df_copy['MntSweetProducts'] + df_copy['MntGoldProds']
df_copy.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Response,TotalSpent
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,4,7,0,0,0,0,0,0,1,1617
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,2,5,0,0,0,0,0,0,0,27
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,10,4,0,0,0,0,0,0,0,776
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,4,6,0,0,0,0,0,0,0,53
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,6,5,0,0,0,0,0,0,0,422

In [86]:
df_copy = df_copy.drop(['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds'], axis=1)

In [87]:

df_copy.drop(['Complain'], axis=1, inplace=True)
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   NumDealsPurchases    2240 non-null   int64
 10  NumWebPurchases      2240 non-null   int64
 11  NumCatalogPurchases  2240 non-null   int64
 12  NumStorePurchases    2240 non-null   int64
 13  NumWebVisitsMonth    2240 non-null   int64
 14  AcceptedCmp3         2240 non-null   int64
 15  AcceptedCmp4         2240 non-null   int64
 16  AcceptedCmp5         2240 non-null   int64
 17  AcceptedCmp1         2240 non-null   int64
 18  AcceptedCmp2         2240 non-null   int64
 19  Response             2240 non-null   int64
 20  TotalSpent           2240 non-null   int64
dtypes: float64(1), int64(17), object(3)
memory usage: 367.6+ KB

In [88]:
df_copy

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumDealsPurchases,...,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,TotalSpent
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,3,...,10,4,7,0,0,0,0,0,1,1617
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,2,...,1,2,5,0,0,0,0,0,0,27
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,1,...,2,10,4,0,0,0,0,0,0,776
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,2,...,0,4,6,0,0,0,0,0,0,53
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,5,...,3,6,5,0,0,0,0,0,0,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,2,...,3,4,5,0,0,0,0,0,0,1341
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,7,...,2,5,7,0,0,0,1,0,0,444
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,1,...,3,13,6,0,1,0,0,0,0,1241
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,2,...,5,10,3,0,0,0,0,0,0,843
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,3,...,1,4,7,0,0,0,0,0,1,172

In [89]:
# Removing CMP columns, as most marketing campaigns were ignored by customers
df_copy.drop(['AcceptedCmp1', 'AcceptedCmp2', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'Response'], axis=1, inplace=True)
df_copy

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,TotalSpent
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,3,8,10,4,7,1617
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,2,1,1,2,5,27
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,1,8,2,10,4,776
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,2,2,0,4,6,53
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,5,5,3,6,5,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,2,9,3,4,5,1341
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,7,8,2,5,7,444
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,1,2,3,13,6,1241
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,2,6,5,10,3,843
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,3,3,1,4,7,172

In [90]:
# checking for null values
df_copy.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
TotalSpent              0
dtype: int64

In [91]:
# This will fill all NaN values in Income with the word 'Unknown'
df_copy['Income'] = df_copy['Income'].fillna('Unknown')
df_copy.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
TotalSpent             0
dtype: int64

In [92]:
df_copy

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,TotalSpent
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,3,8,10,4,7,1617
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,2,1,1,2,5,27
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,1,8,2,10,4,776
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,2,2,0,4,6,53
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,5,5,3,6,5,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,2013-06-13,46,2,9,3,4,5,1341
2236,4001,1946,PhD,Together,64014.0,2,1,2014-06-10,56,7,8,2,5,7,444
2237,7270,1981,Graduation,Divorced,56981.0,0,0,2014-01-25,91,1,2,3,13,6,1241
2238,8235,1956,Master,Together,69245.0,0,1,2014-01-24,8,2,6,5,10,3,843
2239,9405,1954,PhD,Married,52869.0,1,1,2012-10-15,40,3,3,1,4,7,172

In [93]:
# merge the kidhome and teenhome columns into a single column called Total_Children
df_copy['Total_Children'] = df_copy['Kidhome'] + df_copy['Teenhome']
df_copy = df_copy.drop(['Kidhome', 'Teenhome'], axis=1)
df_copy

,ID,Year_Birth,Education,Marital_Status,Income,Dt_Customer,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,TotalSpent,Total_Children
0,5524,1957,Graduation,Single,58138.0,2012-09-04,58,3,8,10,4,7,1617,0
1,2174,1954,Graduation,Single,46344.0,2014-03-08,38,2,1,1,2,5,27,2
2,4141,1965,Graduation,Together,71613.0,2013-08-21,26,1,8,2,10,4,776,0
3,6182,1984,Graduation,Together,26646.0,2014-02-10,26,2,2,0,4,6,53,1
4,5324,1981,PhD,Married,58293.0,2014-01-19,94,5,5,3,6,5,422,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,2013-06-13,46,2,9,3,4,5,1341,1
2236,4001,1946,PhD,Together,64014.0,2014-06-10,56,7,8,2,5,7,444,3
2237,7270,1981,Graduation,Divorced,56981.0,2014-01-25,91,1,2,3,13,6,1241,0
2238,8235,1956,Master,Together,69245.0,2014-01-24,8,2,6,5,10,3,843,1
2239,9405,1954,PhD,Married,52869.0,2012-10-15,40,3,3,1,4,7,172,2

In [94]:
column_list = df_copy.columns.tolist()
print(column_list)

['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Dt_Customer', 'Recency', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'TotalSpent', 'Total_Children']

In [95]:
# Reordering columns for better readability
new_column_order = ['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Total_Children', 'Dt_Customer', 'Recency', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'TotalSpent']
df_copy = df_copy[new_column_order] 
df_copy

,ID,Year_Birth,Education,Marital_Status,Income,Total_Children,Dt_Customer,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,TotalSpent
0,5524,1957,Graduation,Single,58138.0,0,2012-09-04,58,3,8,10,4,7,1617
1,2174,1954,Graduation,Single,46344.0,2,2014-03-08,38,2,1,1,2,5,27
2,4141,1965,Graduation,Together,71613.0,0,2013-08-21,26,1,8,2,10,4,776
3,6182,1984,Graduation,Together,26646.0,1,2014-02-10,26,2,2,0,4,6,53
4,5324,1981,PhD,Married,58293.0,1,2014-01-19,94,5,5,3,6,5,422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,1,2013-06-13,46,2,9,3,4,5,1341
2236,4001,1946,PhD,Together,64014.0,3,2014-06-10,56,7,8,2,5,7,444
2237,7270,1981,Graduation,Divorced,56981.0,0,2014-01-25,91,1,2,3,13,6,1241
2238,8235,1956,Master,Together,69245.0,1,2014-01-24,8,2,6,5,10,3,843
2239,9405,1954,PhD,Married,52869.0,2,2012-10-15,40,3,3,1,4,7,172

In [100]:
#Change income DataType to int64
# Convert 'Unknown' values to 0 or the median income before converting to int64
df_copy['Income'] = df_copy['Income'].replace('Unknown', df_copy[df_copy['Income'] != 'Unknown']['Income'].astype('float64').median())
df_copy['Income'] = df_copy['Income'].astype('int64')
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2240 non-null   int64
 5   Total_Children       2240 non-null   int64
 6   Dt_Customer          2240 non-null   object
 7   Recency              2240 non-null   int64
 8   NumDealsPurchases    2240 non-null   int64
 9   NumWebPurchases      2240 non-null   int64
 10  NumCatalogPurchases  2240 non-null   int64
 11  NumStorePurchases    2240 non-null   int64
 12  NumWebVisitsMonth    2240 non-null   int64
 13  TotalSpent           2240 non-null   int64
dtypes: int64(11), object(3)
memory usage: 245.1+ KB

In [101]:
df_copy.to_csv('cleaned_marketing_campaign1.csv', index=False)